# Generated by Django 3.2 on 2021-08-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('hogarid', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=50)),
                ('Barrio', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=50)),
                ('cargado_010', models.BooleanField(default=False)),
                ('cargado_010_por_gecos', models.CharField(max_length=100, null=True)),
                ('cargado_010_fecha', models.DateTimeField(blank=True, null=True)),
                ('anulado_040', models.BooleanField(default=False)),
                ('anulado_040_por_gecos', models.CharField(max_length=100, null=True)),
                ('anulado_040_fecha', models.DateTimeField(blank=True, null=True)),
                ('aprobado_050', models.BooleanField(default=False)),
                ('aprobado_050_por_gecos', models.CharField(max_length=100, null=True)),
                ('aprobado_050_fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rodados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapa', models.CharField(max_length=100, null=True)),
                ('Marca', models.CharField(max_length=100, null=True)),
                ('Modelo', models.CharField(max_length=100, null=True)),
                ('Tipo', models.CharField(max_length=100, null=True)),
                ('cargado_010', models.BooleanField(default=False)),
                ('cargado_010_por_gecos', models.CharField(max_length=100, null=True)),
                ('cargado_010_fecha', models.DateTimeField(blank=True, null=True)),
                ('anulado_040', models.BooleanField(default=False)),
                ('anulado_040_por_gecos', models.CharField(max_length=100, null=True)),
                ('anulado_040_fecha', models.DateTimeField(blank=True, null=True)),
                ('aprobado_050', models.BooleanField(default=False)),
                ('aprobado_050_por_gecos', models.CharField(max_length=100, null=True)),
                ('aprobado_050_fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=10)),
                ('relacion', models.CharField(max_length=10)),
                ('estadocivil', models.CharField(max_length=20)),
                ('cargado_010', models.BooleanField(default=False)),
                ('cargado_010_por_gecos', models.CharField(max_length=100, null=True)),
                ('cargado_010_fecha', models.DateTimeField(blank=True, null=True)),
                ('anulado_040', models.BooleanField(default=False)),
                ('anulado_040_por_gecos', models.CharField(max_length=100, null=True)),
                ('anulado_040_fecha', models.DateTimeField(blank=True, null=True)),
                ('aprobado_050', models.BooleanField(default=False)),
                ('aprobado_050_por_gecos', models.CharField(max_length=100, null=True)),
                ('aprobado_050_fecha', models.DateTimeField(blank=True, null=True)),
                ('hogar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pgk_master.hogar')),
            ],
        ),
    ]
