# Generated by Django 3.2 on 2021-08-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgk_master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hogar',
            old_name='Barrio',
            new_name='barrio',
        ),
        migrations.RenameField(
            model_name='hogar',
            old_name='Ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='hogar',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='rodados',
            old_name='Chapa',
            new_name='chapa',
        ),
        migrations.RenameField(
            model_name='rodados',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='rodados',
            old_name='Modelo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='rodados',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
